"""add ownership fields, audit events, product events

Revision ID: 1870798baa91
Revises: 171792345784
Create Date: 2026-07-30 20:02:52.087502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1870798baa91'
down_revision: Union[str, Sequence[str], None] = '171792345784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('product_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_events'))
    )
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_companies_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_companies_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_companies_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_companies_owner_id_users'), 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contacts_owner_id_users'), 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_contacts_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_contacts_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_followups_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_followups_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_followups_owner_id_users'), 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_followups_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_meetings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_meetings_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_meetings_owner_id_users'), 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_meetings_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meetings_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_meetings_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_meetings_created_by_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meetings_owner_id'))
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_followups_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_followups_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_followups_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_followups_owner_id'))
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contacts_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contacts_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contacts_owner_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_companies_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_companies_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_owner_id'))
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_product_events_name'))

    op.drop_table('product_events')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_outcome'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
